---
format_version: 10
common:
  deploy-tasks: &deploy-tasks
    - exec:
      command: echo
      arguments:
        - "Deployment of hello-app on ${ENV_NAME} is starting.."
  test-tasks: &test-tasks
    - exec:
      command: echo
      arguments:
        - "Testing of hello-app on ${ENV_NAME} is starting.."

pipelines:
  hello-app:
    group: java-spring-apps
    materials:
      mygit:
        git: https://github.com/Nils-Levandovskis/hello-gradle-ci.git
        branch: main
    stages:
      - build-app:
          jobs:
            build-app:
              tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Building hello-app"
      - deploy-dev:
          environment-variables:
            ENV_NAME: dev
          jobs:
            deploy-dev:
              tasks: *deploy-tasks
      - test-dev:
          environment-variables:
                ENV_NAME: dev
          jobs:
            test-dev:
              tasks: *test-tasks
      - deploy-prd:
          environment-variables:
                ENV_NAME: prd
          jobs:
            deploy-dev:
              tasks:
              - exec: *deploy-tasks
      - test-prd:
          environment-variables:
                ENV_NAME: prd
          jobs:
            test-dev:
              tasks: *test-tasks
