---
format_version: 10
common:
  deploy-tasks: &deploy-tasks
    - exec:
        command: bash
        arguments:
          - -c
          - echo "Deployment of hello-app on ${ENV_NAME} is starting.."
  test-tasks: &test-tasks
    - exec:
        command: echo
        arguments:
          - -c
          - echo "Testing of hello-app on ${ENV_NAME} is starting.."

pipelines:
  hello-app:
    group: java-spring-apps
    materials:
      mygit:
        git: https://github.com/Nils-Levandovskis/hello-gradle-ci.git
        branch: main
    stages:
      - build-app:
          jobs:
            build-app:
              tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Building hello-app"
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - docker build -t nilsleva/hello-app:latest .
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - docker push nilsleva/hello-app:latest
      - deploy-dev:
          environment-variables:
              ENV_NAME: dev
          jobs:
            deploy-dev:
              tasks: *deploy-tasks
      - test-dev:
          environment-variables:
                ENV_NAME: dev
          jobs:
            test-dev:
              tasks: *test-tasks
      - deploy-prd:
          environment-variables:
              ENV_NAME: prd
          jobs:
              deploy-dev:
                tasks: *deploy-tasks
      - test-prd:
          environment-variables:
              ENV_NAME: prd
          jobs:
              test-dev:
                  tasks: *test-tasks
